// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ScreenTimeTracker.ScreenTime.Infrastructure.Persistence;

#nullable disable

namespace ScreenTimeTracker.ScreenTime.Migrations
{
    [DbContext(typeof(ScreenTimeDbContext))]
    [Migration("20260726041707_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("ScreenTimeTracker.ScreenTime.Domain.App", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("AllowMetadataAutoUpdate")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("AppCategoryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExecutablePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("IconPath")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("IconPathLastUpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("MetadataLastUpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProcessName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AppCategoryId");

                    b.HasIndex("ProcessName")
                        .IsUnique();

                    b.ToTable("ScreenTime_Apps");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            AllowMetadataAutoUpdate = false,
                            AppCategoryId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Color = "#636366",
                            IconPathLastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsSystem = true,
                            MetadataLastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Unknown",
                            ProcessName = "Unknown"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            AllowMetadataAutoUpdate = false,
                            AppCategoryId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Color = "#C7C7CC",
                            IconPathLastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsSystem = true,
                            MetadataLastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Idle",
                            ProcessName = "Idle"
                        });
                });

            modelBuilder.Entity("ScreenTimeTracker.ScreenTime.Domain.AppCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IconPath")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("IconPathLastUpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ScreenTime_AppCategories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            Color = "#8E8E93",
                            IconPathLastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsSystem = true,
                            Name = "Uncategorized"
                        });
                });

            modelBuilder.Entity("ScreenTimeTracker.ScreenTime.Domain.AppUsageSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AppId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsOptimized")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EndTime");

                    b.HasIndex("StartTime");

                    b.HasIndex("AppId", "EndTime");

                    b.ToTable("ScreenTime_AppUsageSessions");
                });

            modelBuilder.Entity("ScreenTimeTracker.ScreenTime.Domain.UserSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("ActiveAppUsageSessionAutoSaveInterval")
                        .HasColumnType("TEXT");

                    b.Property<string>("AppIconDirectory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("AppMetadataStaleThreshold")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("AppUsageSessionMergeTolerance")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("AppUsageSessionOptimizationInterval")
                        .HasColumnType("TEXT");

                    b.Property<int>("DayCutoffHour")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("IdleDetectionPollingInterval")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("IdleThreshold")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsIdleDetectionEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("MinValidAppUsageSessionDuration")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ScreenTime_UserSettings");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            ActiveAppUsageSessionAutoSaveInterval = new TimeSpan(0, 0, 0, 15, 0),
                            AppIconDirectory = "./Data/AppIcons",
                            AppMetadataStaleThreshold = new TimeSpan(1, 0, 0, 0, 0),
                            AppUsageSessionMergeTolerance = new TimeSpan(0, 0, 0, 6, 0),
                            AppUsageSessionOptimizationInterval = new TimeSpan(0, 0, 10, 0, 0),
                            DayCutoffHour = 5,
                            IdleDetectionPollingInterval = new TimeSpan(0, 0, 0, 10, 0),
                            IdleThreshold = new TimeSpan(0, 0, 10, 0, 0),
                            IsIdleDetectionEnabled = false,
                            MinValidAppUsageSessionDuration = new TimeSpan(0, 0, 0, 5, 0)
                        });
                });

            modelBuilder.Entity("ScreenTimeTracker.ScreenTime.Domain.App", b =>
                {
                    b.HasOne("ScreenTimeTracker.ScreenTime.Domain.AppCategory", "AppCategory")
                        .WithMany()
                        .HasForeignKey("AppCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AppCategory");
                });

            modelBuilder.Entity("ScreenTimeTracker.ScreenTime.Domain.AppUsageSession", b =>
                {
                    b.HasOne("ScreenTimeTracker.ScreenTime.Domain.App", "App")
                        .WithMany()
                        .HasForeignKey("AppId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("App");
                });
#pragma warning restore 612, 618
        }
    }
}
