// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ScreenTimeTracker.ScreenTime.Infrastructure.Persistence;

#nullable disable

namespace ScreenTimeTracker.ScreenTime.Migrations
{
    [DbContext(typeof(ScreenTimeDbContext))]
    partial class ScreenTimeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("ScreenTimeTracker.ScreenTime.Domain.Apps.App", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("AllowMetadataAutoRefresh")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExecutablePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("IconPath")
                        .HasColumnType("TEXT");

                    b.Property<long>("IconPathLastUpdatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MetadataLastRefreshedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProcessName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ProcessName")
                        .IsUnique();

                    b.ToTable("ScreenTime_Apps");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            AllowMetadataAutoRefresh = false,
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Color = "#636366",
                            IconPathLastUpdatedAt = -62135596800000L,
                            IsSystem = true,
                            MetadataLastRefreshedAt = -62135596800000L,
                            Name = "Unknown",
                            ProcessName = "Unknown"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            AllowMetadataAutoRefresh = false,
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Color = "#C7C7CC",
                            IconPathLastUpdatedAt = -62135596800000L,
                            IsSystem = true,
                            MetadataLastRefreshedAt = -62135596800000L,
                            Name = "Idle",
                            ProcessName = "Idle"
                        });
                });

            modelBuilder.Entity("ScreenTimeTracker.ScreenTime.Domain.Apps.AppCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IconPath")
                        .HasColumnType("TEXT");

                    b.Property<long>("IconPathLastUpdatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ScreenTime_AppCategories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            Color = "#8E8E93",
                            IconPathLastUpdatedAt = -62135596800000L,
                            IsSystem = true,
                            Name = "Uncategorized"
                        });
                });

            modelBuilder.Entity("ScreenTimeTracker.ScreenTime.Domain.Apps.AppUsageSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AppId")
                        .HasColumnType("TEXT");

                    b.Property<long>("EndTime")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsOptimized")
                        .HasColumnType("INTEGER");

                    b.Property<long>("StartTime")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EndTime");

                    b.HasIndex("StartTime");

                    b.HasIndex("AppId", "EndTime");

                    b.ToTable("ScreenTime_AppUsageSessions");
                });

            modelBuilder.Entity("ScreenTimeTracker.ScreenTime.Domain.UserSettings.UserSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "AppTracking", "ScreenTimeTracker.ScreenTime.Domain.UserSettings.UserSettings.AppTracking#AppTrackingSettings", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<TimeSpan>("ActiveUsageSessionAutoSaveInterval")
                                .HasColumnType("TEXT")
                                .HasColumnName("AppTracking_ActiveUsageSessionAutoSaveInterval");

                            b1.Property<string>("IconDirectory")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("AppTracking_IconDirectory");

                            b1.Property<TimeSpan>("MetadataStaleThreshold")
                                .HasColumnType("TEXT")
                                .HasColumnName("AppTracking_MetadataStaleThreshold");

                            b1.Property<TimeSpan>("MinValidUsageSessionDuration")
                                .HasColumnType("TEXT")
                                .HasColumnName("AppTracking_MinValidUsageSessionDuration");

                            b1.Property<TimeSpan>("UsageSessionMergeTolerance")
                                .HasColumnType("TEXT")
                                .HasColumnName("AppTracking_UsageSessionMergeTolerance");

                            b1.Property<TimeSpan>("UsageSessionOptimizationInterval")
                                .HasColumnType("TEXT")
                                .HasColumnName("AppTracking_UsageSessionOptimizationInterval");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "IdleDetection", "ScreenTimeTracker.ScreenTime.Domain.UserSettings.UserSettings.IdleDetection#IdleDetectionSettings", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<TimeSpan>("InactivityThreshold")
                                .HasColumnType("TEXT")
                                .HasColumnName("IdleDetection_InactivityThreshold");

                            b1.Property<bool>("IsEnabled")
                                .HasColumnType("INTEGER")
                                .HasColumnName("IdleDetection_IsEnabled");

                            b1.Property<TimeSpan>("PollingInterval")
                                .HasColumnType("TEXT")
                                .HasColumnName("IdleDetection_PollingInterval");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Regional", "ScreenTimeTracker.ScreenTime.Domain.UserSettings.UserSettings.Regional#RegionalSettings", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("TimeZoneId")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("Regional_TimeZoneId");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "TimeBoundary", "ScreenTimeTracker.ScreenTime.Domain.UserSettings.UserSettings.TimeBoundary#TimeBoundarySettings", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("DayCutoffHour")
                                .HasColumnType("INTEGER")
                                .HasColumnName("TimeBoundary_DayCutoffHour");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "WebsiteTracking", "ScreenTimeTracker.ScreenTime.Domain.UserSettings.UserSettings.WebsiteTracking#WebsiteTrackingSettings", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<TimeSpan>("ActiveUsageSessionAutoSaveInterval")
                                .HasColumnType("TEXT")
                                .HasColumnName("WebsiteTracking_ActiveUsageSessionAutoSaveInterval");

                            b1.Property<string>("IconDirectory")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("WebsiteTracking_IconDirectory");

                            b1.Property<TimeSpan>("MinValidUsageSessionDuration")
                                .HasColumnType("TEXT")
                                .HasColumnName("WebsiteTracking_MinValidUsageSessionDuration");

                            b1.Property<TimeSpan>("UsageSessionMergeTolerance")
                                .HasColumnType("TEXT")
                                .HasColumnName("WebsiteTracking_UsageSessionMergeTolerance");

                            b1.Property<TimeSpan>("UsageSessionOptimizationInterval")
                                .HasColumnType("TEXT")
                                .HasColumnName("WebsiteTracking_UsageSessionOptimizationInterval");
                        });

                    b.HasKey("Id");

                    b.ToTable("ScreenTime_UserSettings");
                });

            modelBuilder.Entity("ScreenTimeTracker.ScreenTime.Domain.Websites.Website", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("AllowMetadataAutoRefresh")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IconPath")
                        .HasColumnType("TEXT");

                    b.Property<long>("IconPathLastUpdatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MetadataLastRefreshedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Host")
                        .IsUnique();

                    b.ToTable("ScreenTime_Websites");
                });

            modelBuilder.Entity("ScreenTimeTracker.ScreenTime.Domain.Websites.WebsiteCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IconPath")
                        .HasColumnType("TEXT");

                    b.Property<long>("IconPathLastUpdatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ScreenTime_WebsiteCategories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            Color = "#8E8E93",
                            IconPathLastUpdatedAt = -62135596800000L,
                            IsSystem = true,
                            Name = "Uncategorized"
                        });
                });

            modelBuilder.Entity("ScreenTimeTracker.ScreenTime.Domain.Websites.WebsiteUsageSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("EndTime")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsOptimized")
                        .HasColumnType("INTEGER");

                    b.Property<long>("StartTime")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("WebsiteId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EndTime");

                    b.HasIndex("StartTime");

                    b.HasIndex("WebsiteId", "EndTime");

                    b.ToTable("ScreenTime_WebsiteUsageSessions");
                });

            modelBuilder.Entity("ScreenTimeTracker.ScreenTime.Domain.Apps.App", b =>
                {
                    b.HasOne("ScreenTimeTracker.ScreenTime.Domain.Apps.AppCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ScreenTimeTracker.ScreenTime.Domain.Apps.AppUsageSession", b =>
                {
                    b.HasOne("ScreenTimeTracker.ScreenTime.Domain.Apps.App", "App")
                        .WithMany()
                        .HasForeignKey("AppId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("App");
                });

            modelBuilder.Entity("ScreenTimeTracker.ScreenTime.Domain.Websites.Website", b =>
                {
                    b.HasOne("ScreenTimeTracker.ScreenTime.Domain.Websites.WebsiteCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ScreenTimeTracker.ScreenTime.Domain.Websites.WebsiteUsageSession", b =>
                {
                    b.HasOne("ScreenTimeTracker.ScreenTime.Domain.Websites.Website", "Website")
                        .WithMany()
                        .HasForeignKey("WebsiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Website");
                });
#pragma warning restore 612, 618
        }
    }
}
