// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(ScreenTimeContext))]
    [Migration("20250610164052_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("Data.Entities.DailyUsage", b =>
                {
                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProcessName")
                        .HasColumnType("TEXT");

                    b.Property<long>("DurationMs")
                        .HasColumnType("INTEGER");

                    b.HasKey("Date", "ProcessName");

                    b.ToTable("DailyUsages");
                });

            modelBuilder.Entity("Data.Entities.HourlyUsage", b =>
                {
                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("Hour")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProcessName")
                        .HasColumnType("TEXT");

                    b.Property<long>("DurationMs")
                        .HasColumnType("INTEGER");

                    b.HasKey("Date", "Hour", "ProcessName");

                    b.ToTable("HourlyUsages");
                });

            modelBuilder.Entity("Data.Entities.ProcessInfo", b =>
                {
                    b.Property<string>("ProcessName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Alias")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExecutablePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("IconPath")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.HasKey("ProcessName");

                    b.ToTable("ProcessInfos");
                });
#pragma warning restore 612, 618
        }
    }
}
