@startuml Component Diagram for Desktop App
!include common.puml

title Component Diagram for Desktop App

Person(user, "用户", "想记录屏幕使用时间")
Container(web_ui, "Web UI", "Vue.js", "前端可视化页面")

ContainerDb(db, "Database", "SQLite", "本地数据库存储")
ContainerDb(json, "Database", "JSON", "本地配置文件存储")
System_Ext(os, "Operating System", "Windows APIs")

Container_Boundary(desktop_app, "Desktop App") {
    Boundary(Presentation, "Presentation Layer") {
        Component(tray_manager, "Tray Manager", "Service", "管理托盘图标与右键菜单")
        Component(tracker_worker, "Tracker Worker", "BackgroundService", "定时触发记录使用情况")
        Component(aggregation_worker, "Aggregation Worker", "BackgroundService", "定时触发聚合使用情况")
        Component(api_controllers, "Web API Controllers", "Controllers", "对外暴露数据接口")
    }

    Boundary(Application, "Application Layer") {
        Component(tracker_service, "Tracker Service", "", "获取当前使用情况并保存原始数据。")
        Component(aggregation_service, "Aggregation Service", "Application Service", "将原始活动日志聚合")
        Component(process_info_management, "ProcessInfo Management", "Application Service", "管理进程信息")
        Component(configuration_handlers, "Configuration Handlers", "CQRS Handlers", "处理应用配置查询修改")
        Component(usage_report_handlers, "UsageReport Handlers", "CQRS Handlers", "处理使用情况报告查询")
        Component(process_info_handlers, "ProcessInfo Handlers", "CQRS Handlers", "处理进程信息查询修改")
    }
    
    Boundary(Domain, "Domain Layer") {
        Component(activity_interval_repository, "ActivityInterval Repository", "Repository", "未聚合的使用情况数据访问")
        Component(hourly_summary_repository, "HourlySummary Repository", "Repository", "聚合后的使用情况数据访问")
        Component(process_info_repository, "ProcessInfo Repository", "Repository", "进程信息数据访问")
        Component(configuration_repository, "Configuration Repository", "", "应用配置")
    }

    Component(usage_report_read_service, "UsageReport Read Service", "", "查询使用情况报告")
    Component(process_info_read_service, "ProcessInfo Read Service", "", "查询进程信息")
    Component(db_access, "Database Access", "EF Core", "数据库访问")
    Component(file_storage, "File Storage", "", "文件存储")
    Component(os_services, "OS Services", "OS API", "调用操作系统 API")
}

' 外部
Rel(user, tray_manager, "托盘交互")
Rel(web_ui, api_controllers, "HTTP/JSON")
Rel(tray_manager, web_ui, "打开")

' Presentation
Rel(api_controllers, process_info_handlers, "Mediator")
Rel(api_controllers, usage_report_handlers, "Mediator")
Rel(api_controllers, configuration_handlers, "Mediator")
Rel(tracker_worker, tracker_service, "Timer")
Rel(tracker_worker, configuration_handlers, "Mediator")
Rel(aggregation_worker, aggregation_service, "Timer")
Rel(aggregation_worker, configuration_handlers, "Mediator")

' Application
Rel(tracker_service, configuration_repository, "")
Rel(tracker_service, process_info_management, "")
Rel(tracker_service, activity_interval_repository, "")
Rel(tracker_service, os_services, "")

Rel(aggregation_service, configuration_repository, "")
Rel(aggregation_service, activity_interval_repository, "")
Rel(aggregation_service, hourly_summary_repository, "")

Rel(process_info_management, configuration_repository, "")
Rel(process_info_management, process_info_repository, "")
Rel(process_info_management, os_services, "")

Rel(process_info_handlers, process_info_repository, "")
Rel(process_info_handlers, process_info_read_service, "read")
Rel(usage_report_handlers, usage_report_read_service, "read")
Rel(configuration_handlers, configuration_repository, "")

' Domain
Rel(process_info_repository, db_access, "")
Rel(activity_interval_repository, db_access, "")
Rel(hourly_summary_repository, db_access, "")
Rel(configuration_repository, file_storage, "")

' Infrastructure
Rel(usage_report_read_service, db_access, "")
Rel(process_info_read_service, db_access, "")
Rel(db_access, db, "EF Core")
Rel(file_storage, json, "Json")
Rel(os_services, os, "Win32 APIs")

@enduml
