<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>ScreenTimeTracker.ArchitectureTests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="xunit.runner.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="TngTech.ArchUnitNET.xUnitV3" />
    <PackageReference Include="xunit.v3.mtp-v2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Hosts\ScreenTimeTracker.Desktop\ScreenTimeTracker.Desktop.csproj" />
    <ProjectReference Include="..\..\src\Modules\DesktopSettings\ScreenTimeTracker.DesktopSettings.Contracts\ScreenTimeTracker.DesktopSettings.Contracts.csproj" />
    <ProjectReference Include="..\..\src\Modules\DesktopSettings\ScreenTimeTracker.DesktopSettings\ScreenTimeTracker.DesktopSettings.csproj" />
    <ProjectReference Include="..\..\src\Modules\ScreenTime\ScreenTimeTracker.ScreenTime\ScreenTimeTracker.ScreenTime.csproj" />
    <ProjectReference Include="..\..\src\ScreenTimeTracker.BuildingBlocks\ScreenTimeTracker.BuildingBlocks.csproj" />
  </ItemGroup>
</Project>
