// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ScreenTimeTracker.Infrastructure.Persistence.DbContexts;

#nullable disable

namespace ScreenTimeTracker.Infrastructure.Migrations
{
    [DbContext(typeof(ScreenTimeDbContext))]
    [Migration("20251115061927_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("ScreenTimeTracker.Infrastructure.Persistence.Models.ActivityIntervalEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ProcessInfoEntityId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProcessInfoEntityId");

                    b.HasIndex("Timestamp");

                    b.ToTable("ActivityIntervals");
                });

            modelBuilder.Entity("ScreenTimeTracker.Infrastructure.Persistence.Models.HourlySummaryEntity", b =>
                {
                    b.Property<Guid>("ProcessInfoEntityId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Hour")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalDurationMilliseconds")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProcessInfoEntityId", "Hour");

                    b.ToTable("HourlySummaries");
                });

            modelBuilder.Entity("ScreenTimeTracker.Infrastructure.Persistence.Models.ProcessInfoEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Alias")
                        .HasColumnType("TEXT");

                    b.Property<bool>("AutoUpdate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExecutablePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("IconPath")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastAutoUpdated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ProcessInfos");
                });

            modelBuilder.Entity("ScreenTimeTracker.Infrastructure.Persistence.Models.ActivityIntervalEntity", b =>
                {
                    b.HasOne("ScreenTimeTracker.Infrastructure.Persistence.Models.ProcessInfoEntity", "ProcessInfoEntity")
                        .WithMany("ActivityIntervals")
                        .HasForeignKey("ProcessInfoEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProcessInfoEntity");
                });

            modelBuilder.Entity("ScreenTimeTracker.Infrastructure.Persistence.Models.HourlySummaryEntity", b =>
                {
                    b.HasOne("ScreenTimeTracker.Infrastructure.Persistence.Models.ProcessInfoEntity", "ProcessInfoEntity")
                        .WithMany("HourlySummaries")
                        .HasForeignKey("ProcessInfoEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProcessInfoEntity");
                });

            modelBuilder.Entity("ScreenTimeTracker.Infrastructure.Persistence.Models.ProcessInfoEntity", b =>
                {
                    b.Navigation("ActivityIntervals");

                    b.Navigation("HourlySummaries");
                });
#pragma warning restore 612, 618
        }
    }
}
