/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    AppMenu: typeof import('./src/components/AppMenu.vue')['default']
    Button: typeof import('primevue/button')['default']
    ButtonGroup: typeof import('primevue/buttongroup')['default']
    Card: typeof import('primevue/card')['default']
    CascadeSelect: typeof import('primevue/cascadeselect')['default']
    Chart: typeof import('primevue/chart')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    Column: typeof import('primevue/column')['default']
    ConfirmDialog: typeof import('primevue/confirmdialog')['default']
    DataTable: typeof import('primevue/datatable')['default']
    DatePicker: typeof import('primevue/datepicker')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Fieldset: typeof import('primevue/fieldset')['default']
    Image: typeof import('primevue/image')['default']
    InputGroup: typeof import('primevue/inputgroup')['default']
    InputGroupAddon: typeof import('primevue/inputgroupaddon')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Listbox: typeof import('primevue/listbox')['default']
    MultiSelect: typeof import('primevue/multiselect')['default']
    Panel: typeof import('primevue/panel')['default']
    ProcessUsageChart: typeof import('./src/components/ProcessUsageChart.vue')['default']
    ProcessUsageRank: typeof import('./src/components/ProcessUsageRank.vue')['default']
    ProgressBar: typeof import('primevue/progressbar')['default']
    RadioButton: typeof import('primevue/radiobutton')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('primevue/select')['default']
    SelectButton: typeof import('primevue/selectbutton')['default']
    Stepper: typeof import('./src/components/Stepper.vue')['default']
    Test: typeof import('./src/components/Test.vue')['default']
    Textarea: typeof import('primevue/textarea')['default']
    TimeStepper: typeof import('./src/components/TimeStepper.vue')['default']
    ToggleSwitch: typeof import('primevue/toggleswitch')['default']
    TotalUsage: typeof import('./src/components/TotalUsage.vue')['default']
    TotalUsageChart: typeof import('./src/components/TotalUsageChart.vue')['default']
    UsageDistribution: typeof import('./src/components/UsageDistribution.vue')['default']
  }
}
